USE BD_BIBLIOTECA;

CREATE TABLE AUTOR
(AUTORID          INT          NOT NULL,
 NOME             VARCHAR(50)  NOT NULL,
 ENDERECO         VARCHAR(50),
 SEXO             CHAR(1),
 DATA_NASCIMENTO  DATETIME,
 CONSTRAINT PK_AUTOR
   PRIMARY KEY (AUTORID)
);

CREATE TABLE EDITORA
(EDITORAID		INT         NOT NULL,
 NOME			VARCHAR(50) NOT NULL,
 ENDERECO       VARCHAR(50),
 LOCALIDADE     VARCHAR(20),
 COD_POSTAL		VARCHAR(10),
 CONSTRAINT PK_EDITORA
   PRIMARY KEY (EDITORAID)
);

CREATE TABLE LIVRO
(ISBN			INT         NOT NULL,
 TITULO			VARCHAR(20) NOT NULL,
 ANO			DATETIME,
 EDICAO			VARCHAR(10),
 EDITORAID		INT,
 CONSTRAINT PK_LIVRO
    PRIMARY KEY (ISBN),
 CONSTRAINT FK_LIVRO_EDITORA
	FOREIGN KEY (EDITORAID) REFERENCES EDITORA(EDITORAID)
);

CREATE TABLE LIVRO_AUTOR
(ISBN			INT         NOT NULL,
 AUTORID		INT         NOT NULL,
 CONSTRAINT PK_LIVRO_AUTOR
   PRIMARY KEY (ISBN, AUTORID),
 CONSTRAINT FK_LIVROAUTOR_AUTOR
   FOREIGN KEY (AUTORID) REFERENCES AUTOR (AUTORID),
 CONSTRAINT FK_LIVROAUTOR_LIVRO
   FOREIGN KEY (ISBN) REFERENCES LIVRO (ISBN)
);

CREATE TABLE PALAVRA_CHAVE
(PALAVRAID     INT         NOT NULL,
 PALAVRA       VARCHAR(15) NOT NULL,
 CONSTRAINT PK_PALAVRA_CHAVE
   PRIMARY KEY (PALAVRAID)
);

CREATE TABLE LIVRO_PALAVRA
(ISBN			INT         NOT NULL,
 PALAVRAID		INT         NOT NULL,
 CONSTRAINT PK_LIVRO_PALAVRA
   PRIMARY KEY (ISBN, PALAVRAID),
 CONSTRAINT FK_LIVROPALAVRA_AUTOR
   FOREIGN KEY (PALAVRAID) REFERENCES PALAVRA_CHAVE (PALAVRAID),
 CONSTRAINT FK_LIVROPALAVRA_LIVRO
   FOREIGN KEY (ISBN) REFERENCES LIVRO (ISBN)
);

CREATE TABLE EXEMPLAR
(EXEMPLARID		INT         NOT NULL,
 ISBN			INT         NOT NULL,
 DATAAQUISICAO	DATETIME	NOT NULL,
 CONSTRAINT PK_EXEMPLAR
   PRIMARY KEY (EXEMPLARID,ISBN),
 CONSTRAINT FK_EXEMPLAR_LIVRO
   FOREIGN KEY (ISBN) REFERENCES LIVRO (ISBN)
);

