set sql_safe_updates=0;
DELIMITER //
CREATE PROCEDURE IMC(NOME VARCHAR(20),PESO FLOAT, ALTURA FLOAT)
BEGIN

DECLARE IMC FLOAT;
DECLARE SITU VARCHAR(10);

SET IMC = PESO / (ALTURA * ALTURA);

SET SITU = CASE
			WHEN IMC <=10 THEN 'SUBPESO'
			WHEN IMC <=25 THEN 'NORMAL'
			WHEN IMC <=29.9 THEN 'SOBREPESO'
			ELSE 'OBESO'
            END;

END//
DBMS_OUTPUT.PUT_LINE (NOME || ', seu ICM é '|| CAST(IMC AS VARCHAR(10)) ||' e você está '|| SITU);
DELIMITER ;

call IMC('YNOA', 74, 1.72);
