set sql_safe_updates=0;
DECLARE @PESO FLOAT, @ALTURA FLOAT, @IMC FLOAT, @SITU VARCHAR(10), @NOME VARCHAR(20)

SET @NOME = ynoa
SET @PESO = 76.0
SET @ALTURA = 1.72
SET @IMC = @PESO / (@ALTURA * @ALTURA)

SET @SITU = CASE
			WHEN @IMC <=10 THEN 'SUBPESO'
			WHEN @IMC <=25 THEN 'NORMAL'
			WHEN @IMC <=29.9 THEN 'SOBREPESO'
			ELSE 'OBESO'
END
PRINT @NOME + ', seu ICM é '+ CAST(@IMC AS VARCHAR(10)) + ' e você está '+ @SITU